"""Add parent_transaction_id with cascade delete

Revision ID: 8219364b7c98
Revises: 2f074c0708fa
Create Date: 2025-05-25 16:39:09.806284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8219364b7c98'
down_revision: Union[str, None] = '2f074c0708fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.create_table(
        'transactions_new',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('type', sa.String(10), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('amount', sa.Numeric(10, 2), nullable=False),
        sa.Column('payee', sa.String(), nullable=False),
        sa.Column('category_id', sa.Integer(), sa.ForeignKey('categories.id')),
        sa.Column('tag_id', sa.Integer(), sa.ForeignKey('tags.id')),
        sa.Column(
            'parent_transaction_id',
            sa.Integer(),
            sa.ForeignKey('transactions.id', ondelete='CASCADE') 
        )
    )

    op.execute("""
        INSERT INTO transactions_new (
            id, type, date, amount, payee, category_id, tag_id, parent_transaction_id
        )
        SELECT id, type, date, amount, payee, category_id, tag_id, parent_transaction_id FROM transactions
    """)

    op.drop_table('transactions')
    op.rename_table('transactions_new', 'transactions')



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
